### ISSUE TITLE
Missing dependency on json_pure

### ISSUE THREAD

**Issue by joschi** [santana/puppet-cleaner#1]
puppet-clean doesn't start if `json_pure` is not installed.

```
# puppet-clean 
/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'json_pure' (>= 0) among 49 total gem(s) (Gem::LoadError)
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1196:in `block in activate_dependencies'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1185:in `each'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1185:in `activate_dependencies'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1167:in `activate'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1199:in `block in activate_dependencies'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1185:in `each'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1185:in `activate_dependencies'
        from /usr/lib/ruby/2.0.0/rubygems/specification.rb:1167:in `activate'
        from /usr/lib/ruby/2.0.0/rubygems.rb:181:in `rescue in try_activate'
        from /usr/lib/ruby/2.0.0/rubygems.rb:178:in `try_activate'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:109:in `rescue in require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /usr/lib/ruby/gems/2.0.0/gems/puppet-cleaner-0.1.0/lib/puppet-cleaner.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /usr/lib/ruby/gems/2.0.0/gems/puppet-cleaner-0.1.0/bin/puppet-clean:4:in `<top (required)>'
        from /usr/bin/puppet-clean:23:in `load'
        from /usr/bin/puppet-clean:23:in `<main>'
```

**Comment by santana** [comment]
Hi joschi,

thanks again for your report. It looks like it's a Ruby 2.0 issue, since I can run it on 1.8.7 successfully. I'll give it a try on Ruby 2.0 to see what's wrong.

**Comment by santana** [comment]
Hi joschi,

after googling a bit, I've found that there's probably an issue with your json or json_pure gem installation. puppet-cleaner doesn't depend in any way on json or json_pure though.

This link may probably help you, which basically talks about removing your json gems and installing the one you need:

https://groups.google.com/forum/?fromgroups=#!topic/railsinstaller/QUNyqliOYH4

**Comment by joschi** [comment]
Thanks for investigating the issue! I'll have another look at my Ruby setup.
